-- Personal Recipe Book — seeds.sql
-- Generated from project/data.jsx + project/pantry-data.jsx.
-- Assumes the admin row already lives at users.id = 1 (created by install.php
-- between schema.sql and this file).

SET NAMES utf8mb4;

-- Default settings row for the seeded user.
INSERT INTO user_settings (user_id) VALUES (1)
  ON DUPLICATE KEY UPDATE user_id = user_id;

-- ---- Recipes ----
INSERT INTO recipes (id, user_id, slug, title, cuisine, summary, time_minutes, servings, difficulty, glyph, color, photo_url) VALUES
  (1, 1, 'r1', 'Cacio e Pepe', 'Italian', 'Three-ingredient Roman pasta. Pecorino + black pepper magic.', 20, 2, 'Easy', '🍝', 'butter', 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=900&q=70'),
  (2, 1, 'r2', 'Mapo Tofu', 'Sichuanese', 'Numbing, spicy, glossy. The platonic ideal of rice topping.', 25, 4, 'Medium', '🌶️', 'coral', 'https://images.unsplash.com/photo-1582452757214-2376f6a17a72?w=900&q=70'),
  (3, 1, 'r3', 'Shakshuka', 'North African', 'Eggs poached in a smoky, spiced tomato sea. Bread mandatory.', 30, 4, 'Easy', '🍳', 'peach', 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=900&q=70'),
  (4, 1, 'r4', 'Khao Soi', 'Northern Thai', 'Curry-noodle soup with crispy noodle crown. Chiang Mai''s greatest hit.', 45, 4, 'Medium', '🍜', 'butter', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=900&q=70'),
  (5, 1, 'r5', 'Chana Masala', 'Indian', 'Chickpeas in a tangy, spice-deep tomato gravy. Pantry hero.', 40, 4, 'Easy', '🫘', 'butter', 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900&q=70'),
  (6, 1, 'r6', 'Miso-Glazed Salmon', 'Japanese', 'Lacquered, sweet-savory, pairs with literally anything green.', 25, 2, 'Easy', '🐟', 'coral', 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=900&q=70'),
  (7, 1, 'r7', 'Tacos al Pastor', 'Mexican', 'Pineapple-marinated pork. The trompo at home, sort of.', 60, 4, 'Medium', '🌮', 'peach', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=900&q=70'),
  (8, 1, 'r8', 'Tabbouleh', 'Lebanese', 'Parsley salad with bulgur as a guest. Bright, herbal, addictive.', 20, 4, 'Easy', '🥗', 'lime', 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=900&q=70'),
  (9, 1, 'r9', 'Bibimbap', 'Korean', 'Rainbow rice bowl. Each vegetable seasoned solo, then assembled.', 35, 2, 'Medium', '🍚', 'coral', 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=900&q=70'),
  (10, 1, 'r10', 'Ratatouille', 'French', 'Provençal vegetable confit. Slow, gentle, gets better overnight.', 75, 6, 'Medium', '🍆', 'lilac', 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=900&q=70'),
  (11, 1, 'r11', 'Banana Bread', 'American', 'Brown-butter, dark-sugar banana bread. Use the saddest bananas.', 70, 8, 'Easy', '🍌', 'butter', 'https://images.unsplash.com/photo-1605286658671-f7d63a4cc8ec?w=900&q=70'),
  (12, 1, 'r12', 'Greek Lemon Chicken', 'Greek', 'Sheet-pan chicken & potatoes swimming in lemony, oregano-y juices.', 60, 4, 'Easy', '🍋', 'butter', 'https://images.unsplash.com/photo-1598103442257-8c4b7d6c6f6c?w=900&q=70');

-- ---- Recipe tags ----
INSERT INTO recipe_tags (recipe_id, tag) VALUES
  (1, 'weeknight'),
  (1, 'pasta'),
  (1, '5-ingredient'),
  (2, 'spicy'),
  (2, 'weeknight'),
  (2, 'vegetarian-option'),
  (3, 'brunch'),
  (3, 'vegetarian'),
  (3, 'one-pan'),
  (4, 'noodles'),
  (4, 'spicy'),
  (4, 'coconut'),
  (5, 'vegan'),
  (5, 'pantry'),
  (5, 'weeknight'),
  (6, 'weeknight'),
  (6, 'high-protein'),
  (6, '4-ingredient'),
  (7, 'weekend'),
  (7, 'pork'),
  (7, 'crowd-pleaser'),
  (8, 'vegan'),
  (8, 'salad'),
  (8, 'no-cook'),
  (9, 'rice-bowl'),
  (9, 'vegetable'),
  (9, 'fridge-clean'),
  (10, 'vegan'),
  (10, 'meal-prep'),
  (10, 'summer'),
  (11, 'bake'),
  (11, 'breakfast'),
  (11, 'one-bowl'),
  (12, 'sheet-pan'),
  (12, 'sunday'),
  (12, 'crowd-pleaser');

-- ---- Ingredients ----
INSERT INTO ingredients (recipe_id, position, qty, unit, name, aisle) VALUES
  (1, 0, 200, 'g', 'spaghetti', 'Pantry'),
  (1, 1, 80, 'g', 'pecorino romano', 'Dairy'),
  (1, 2, 2, 'tsp', 'black pepper', 'Spices'),
  (1, 3, 1, 'pinch', 'sea salt', 'Spices'),
  (2, 0, 1, 'block', 'silken tofu', 'Produce'),
  (2, 1, 200, 'g', 'ground pork', 'Meat & Fish'),
  (2, 2, 2, 'tbsp', 'doubanjiang', 'Pantry'),
  (2, 3, 1, 'tbsp', 'douchi (fermented black beans)', 'Pantry'),
  (2, 4, 3, 'cloves', 'garlic', 'Produce'),
  (2, 5, 1, 'thumb', 'ginger', 'Produce'),
  (2, 6, 1, 'tsp', 'sichuan peppercorns', 'Spices'),
  (2, 7, 2, 'stalks', 'scallions', 'Produce'),
  (2, 8, 1, 'cup', 'chicken stock', 'Pantry'),
  (3, 0, 1, '', 'yellow onion', 'Produce'),
  (3, 1, 1, '', 'red bell pepper', 'Produce'),
  (3, 2, 4, 'cloves', 'garlic', 'Produce'),
  (3, 3, 1, 'tsp', 'cumin', 'Spices'),
  (3, 4, 1, 'tsp', 'smoked paprika', 'Spices'),
  (3, 5, 1, 'can', 'whole tomatoes', 'Pantry'),
  (3, 6, 4, '', 'eggs', 'Dairy'),
  (3, 7, 50, 'g', 'feta', 'Dairy'),
  (3, 8, 1, 'bunch', 'parsley', 'Produce'),
  (4, 0, 4, '', 'chicken thighs', 'Meat & Fish'),
  (4, 1, 3, 'tbsp', 'khao soi paste', 'Pantry'),
  (4, 2, 400, 'ml', 'coconut milk', 'Pantry'),
  (4, 3, 500, 'ml', 'chicken stock', 'Pantry'),
  (4, 4, 400, 'g', 'fresh egg noodles', 'Produce'),
  (4, 5, 2, 'tbsp', 'fish sauce', 'Pantry'),
  (4, 6, 1, 'tbsp', 'palm sugar', 'Pantry'),
  (4, 7, 1, '', 'lime', 'Produce'),
  (4, 8, 1, 'small', 'shallot', 'Produce'),
  (4, 9, 1, 'bunch', 'cilantro', 'Produce'),
  (5, 0, 2, 'cans', 'chickpeas', 'Pantry'),
  (5, 1, 1, '', 'onion', 'Produce'),
  (5, 2, 2, '', 'tomatoes', 'Produce'),
  (5, 3, 4, 'cloves', 'garlic', 'Produce'),
  (5, 4, 1, 'thumb', 'ginger', 'Produce'),
  (5, 5, 1, 'tsp', 'cumin seeds', 'Spices'),
  (5, 6, 2, 'tsp', 'garam masala', 'Spices'),
  (5, 7, 1, 'tsp', 'turmeric', 'Spices'),
  (5, 8, 1, 'tsp', 'amchur (dried mango)', 'Spices'),
  (5, 9, 1, '', 'lemon', 'Produce'),
  (6, 0, 2, 'fillets', 'salmon', 'Meat & Fish'),
  (6, 1, 3, 'tbsp', 'white miso', 'Pantry'),
  (6, 2, 2, 'tbsp', 'mirin', 'Pantry'),
  (6, 3, 1, 'tbsp', 'soy sauce', 'Pantry'),
  (6, 4, 1, 'tbsp', 'maple syrup', 'Pantry'),
  (6, 5, 1, '', 'scallion', 'Produce'),
  (7, 0, 1, 'kg', 'pork shoulder', 'Meat & Fish'),
  (7, 1, 3, '', 'guajillo chiles', 'Spices'),
  (7, 2, 2, '', 'ancho chiles', 'Spices'),
  (7, 3, 0.5, '', 'pineapple', 'Produce'),
  (7, 4, 4, 'cloves', 'garlic', 'Produce'),
  (7, 5, 2, 'tbsp', 'achiote paste', 'Pantry'),
  (7, 6, 2, 'tbsp', 'apple cider vinegar', 'Pantry'),
  (7, 7, 12, '', 'corn tortillas', 'Bakery'),
  (7, 8, 1, '', 'white onion', 'Produce'),
  (7, 9, 1, 'bunch', 'cilantro', 'Produce'),
  (8, 0, 3, 'bunches', 'flat-leaf parsley', 'Produce'),
  (8, 1, 0.25, 'cup', 'fine bulgur', 'Pantry'),
  (8, 2, 3, '', 'roma tomatoes', 'Produce'),
  (8, 3, 4, 'stalks', 'scallions', 'Produce'),
  (8, 4, 0.5, 'bunch', 'mint', 'Produce'),
  (8, 5, 2, '', 'lemons', 'Produce'),
  (8, 6, 0.33, 'cup', 'olive oil', 'Pantry'),
  (9, 0, 2, 'cups', 'cooked short-grain rice', 'Pantry'),
  (9, 1, 200, 'g', 'ground beef', 'Meat & Fish'),
  (9, 2, 1, 'bunch', 'spinach', 'Produce'),
  (9, 3, 1, '', 'carrot', 'Produce'),
  (9, 4, 1, '', 'zucchini', 'Produce'),
  (9, 5, 100, 'g', 'shiitake mushrooms', 'Produce'),
  (9, 6, 200, 'g', 'bean sprouts', 'Produce'),
  (9, 7, 2, '', 'eggs', 'Dairy'),
  (9, 8, 3, 'tbsp', 'gochujang', 'Pantry'),
  (9, 9, 2, 'tsp', 'sesame oil', 'Pantry'),
  (9, 10, 1, 'tbsp', 'sesame seeds', 'Pantry'),
  (10, 0, 1, '', 'eggplant', 'Produce'),
  (10, 1, 2, '', 'zucchini', 'Produce'),
  (10, 2, 1, '', 'red bell pepper', 'Produce'),
  (10, 3, 1, '', 'yellow bell pepper', 'Produce'),
  (10, 4, 1, '', 'onion', 'Produce'),
  (10, 5, 4, '', 'tomatoes', 'Produce'),
  (10, 6, 6, 'cloves', 'garlic', 'Produce'),
  (10, 7, 1, 'sprig', 'thyme', 'Produce'),
  (10, 8, 1, '', 'bay leaf', 'Spices'),
  (10, 9, 0.33, 'cup', 'olive oil', 'Pantry'),
  (11, 0, 3, '', 'very ripe bananas', 'Produce'),
  (11, 1, 115, 'g', 'butter', 'Dairy'),
  (11, 2, 150, 'g', 'dark brown sugar', 'Pantry'),
  (11, 3, 2, '', 'eggs', 'Dairy'),
  (11, 4, 1, 'tsp', 'vanilla extract', 'Pantry'),
  (11, 5, 200, 'g', 'flour', 'Pantry'),
  (11, 6, 1, 'tsp', 'baking soda', 'Pantry'),
  (11, 7, 0.5, 'tsp', 'salt', 'Spices'),
  (11, 8, 1, 'tsp', 'cinnamon', 'Spices'),
  (12, 0, 4, '', 'chicken thighs (bone-in)', 'Meat & Fish'),
  (12, 1, 800, 'g', 'yukon gold potatoes', 'Produce'),
  (12, 2, 2, '', 'lemons', 'Produce'),
  (12, 3, 6, 'cloves', 'garlic', 'Produce'),
  (12, 4, 2, 'tbsp', 'dried oregano', 'Spices'),
  (12, 5, 0.33, 'cup', 'olive oil', 'Pantry'),
  (12, 6, 1, 'cup', 'chicken stock', 'Pantry');

-- ---- Steps ----
INSERT INTO steps (recipe_id, position, text) VALUES
  (1, 0, 'Bring a small pot of salted water to a boil. Less water = starchier = silkier sauce.'),
  (1, 1, 'Toast cracked black pepper in a dry pan until fragrant, about 30 seconds.'),
  (1, 2, 'Cook spaghetti 1 minute under package time. Reserve a full mug of pasta water.'),
  (1, 3, 'Off heat, toss pasta with pepper, then add grated pecorino in 3 stages with splashes of pasta water, stirring vigorously between each.'),
  (1, 4, 'The sauce should coat each strand. Plate immediately, more pepper on top.'),
  (2, 0, 'Cube tofu into 1-inch pieces. Slip into salted simmering water; turn off heat.'),
  (2, 1, 'Toast Sichuan peppercorns in a dry wok until fragrant. Grind half, save half.'),
  (2, 2, 'Brown pork in oil until crisp. Push aside; fry doubanjiang and douchi until oil turns red.'),
  (2, 3, 'Add minced garlic and ginger, then stock. Slip tofu in carefully.'),
  (2, 4, 'Simmer 4 minutes. Thicken with cornstarch slurry in 3 additions until glossy.'),
  (2, 5, 'Top with scallions and remaining ground peppercorn.'),
  (3, 0, 'Sweat diced onion and pepper in olive oil 8 minutes until soft.'),
  (3, 1, 'Add garlic, cumin, paprika. Stir 30 seconds till you can smell them across the room.'),
  (3, 2, 'Crush tomatoes in by hand. Simmer 10 minutes till jammy.'),
  (3, 3, 'Make 4 wells with a spoon. Crack an egg into each.'),
  (3, 4, 'Cover and cook 5–7 minutes — whites just set, yolks runny.'),
  (3, 5, 'Crumble feta, shower with parsley. Serve with bread for dragging.'),
  (4, 0, 'Fry a quarter of the noodles in hot oil until puffy and crisp. Drain.'),
  (4, 1, 'In the same pot, fry curry paste in coconut cream until oil splits.'),
  (4, 2, 'Add chicken, brown lightly. Pour in remaining coconut milk and stock.'),
  (4, 3, 'Simmer 25 minutes till chicken is tender. Season with fish sauce, palm sugar.'),
  (4, 4, 'Boil remaining noodles 2 minutes; drain.'),
  (4, 5, 'Bowl: noodles, ladle of curry, chicken, crispy noodle crown, shallots, cilantro, lime.'),
  (5, 0, 'Bloom cumin seeds in oil till they sizzle and pop.'),
  (5, 1, 'Fry diced onion till deep gold, 12 minutes — patience pays.'),
  (5, 2, 'Add ginger-garlic paste, cook 1 minute. Add tomatoes; mash and cook to a paste.'),
  (5, 3, 'Stir in turmeric, garam masala, amchur, salt. Add chickpeas with a splash of their liquid.'),
  (5, 4, 'Simmer 15 minutes. Mash some chickpeas against the pan to thicken.'),
  (5, 5, 'Finish with a big squeeze of lemon. Serve with rice or roti.'),
  (6, 0, 'Whisk miso, mirin, soy, maple. Reserve 2 tbsp for glazing.'),
  (6, 1, 'Marinate salmon in the rest 15 minutes (or up to overnight).'),
  (6, 2, 'Heat broiler. Place salmon skin-down on foil-lined tray.'),
  (6, 3, 'Broil 6–8 minutes, brushing with reserved glaze halfway through.'),
  (6, 4, 'It''s done when the top is mahogany and the flesh flakes. Top with sliced scallion.'),
  (7, 0, 'Toast and rehydrate dried chiles in hot water 15 minutes.'),
  (7, 1, 'Blend chiles with half the pineapple, garlic, achiote, vinegar, salt — that''s the adobo.'),
  (7, 2, 'Slice pork thin against the grain. Marinate 4+ hours.'),
  (7, 3, 'Sear pork in a screaming-hot pan in batches; do not crowd.'),
  (7, 4, 'Char remaining pineapple in the same pan; dice it.'),
  (7, 5, 'Warm tortillas. Pile pork, pineapple, white onion, cilantro. Lime hard.'),
  (8, 0, 'Soak bulgur in cold water 10 minutes; drain and squeeze dry.'),
  (8, 1, 'Pick parsley leaves only. Chop very finely with a sharp knife — never blitz.'),
  (8, 2, 'Dice tomatoes and scallions. Chop mint at the last second.'),
  (8, 3, 'Combine everything with bulgur. Dress with lemon juice, olive oil, salt.'),
  (8, 4, 'Rest 10 minutes before serving so flavors marry. Eat with romaine spears.'),
  (9, 0, 'Marinate beef in soy, sugar, sesame oil, garlic.'),
  (9, 1, 'Blanch spinach 30s; squeeze; dress with sesame oil, salt, garlic.'),
  (9, 2, 'Stir-fry carrot, then zucchini, then mushrooms — each separately, lightly salted.'),
  (9, 3, 'Blanch bean sprouts; dress like spinach.'),
  (9, 4, 'Brown beef hard. Fry eggs sunny-side, crispy edges.'),
  (9, 5, 'Bowl: rice, vegetables in arcs, beef, egg in middle, gochujang on top, sesame seeds.'),
  (10, 0, 'Cut eggplant into chunks; salt; rest 20 minutes; pat dry.'),
  (10, 1, 'Sear each vegetable separately in olive oil until just browned, then remove.'),
  (10, 2, 'In the same pot, sweat onion till soft. Add garlic, then tomatoes, thyme, bay.'),
  (10, 3, 'Return all vegetables. Add splash of water. Cover and stew on low 35 minutes.'),
  (10, 4, 'Uncover, reduce 10 minutes. Adjust salt. Best after a night in the fridge.'),
  (11, 0, 'Brown the butter in a small pan until nutty and amber. Cool slightly.'),
  (11, 1, 'Mash bananas in a bowl. Whisk in butter, sugar, eggs, vanilla.'),
  (11, 2, 'Add flour, soda, salt, cinnamon. Fold just until no streaks.'),
  (11, 3, 'Pour into a greased loaf pan. Bake at 175°C / 350°F for 55 minutes.'),
  (11, 4, 'Cool 15 minutes in pan, then turn out. Slice thick.'),
  (12, 0, 'Cut potatoes into thick wedges. Toss in roasting tray with oil, oregano, garlic, salt.'),
  (12, 1, 'Squeeze lemon juice all over; tuck spent halves in. Pour stock around.'),
  (12, 2, 'Nestle chicken on top, skin up. Brush with more oil, salt heavily.'),
  (12, 3, 'Roast at 200°C / 400°F for 45 minutes, basting once at 25 minutes.'),
  (12, 4, 'Crank to 220°C / 425°F for 10 more minutes till skin is shattering.'),
  (12, 5, 'Rest 10 minutes. Serve in the tray with the juices.');

-- ---- Pantry staples ----
INSERT INTO pantry_items (user_id, name, key_normalized, in_stock, category) VALUES
  (1, 'salt', 'salt', 1, 'Spices'),
  (1, 'black pepper', 'black pepper', 1, 'Spices'),
  (1, 'cumin', 'cumin', 1, 'Spices'),
  (1, 'paprika', 'paprika', 1, 'Spices'),
  (1, 'cinnamon', 'cinnamon', 1, 'Spices'),
  (1, 'dried oregano', 'dried oregano', 1, 'Spices'),
  (1, 'red pepper flakes', 'red pepper flakes', 1, 'Spices'),
  (1, 'onion', 'onion', 1, 'Produce'),
  (1, 'garlic', 'garlic', 1, 'Produce'),
  (1, 'lemon', 'lemon', 1, 'Produce'),
  (1, 'ginger', 'ginger', 1, 'Produce'),
  (1, 'butter', 'butter', 1, 'Dairy'),
  (1, 'eggs', 'eggs', 1, 'Dairy'),
  (1, 'milk', 'milk', 1, 'Dairy'),
  (1, 'parmesan', 'parmesan', 1, 'Dairy'),
  (1, 'olive oil', 'olive oil', 1, 'Pantry'),
  (1, 'vegetable oil', 'vegetable oil', 1, 'Pantry'),
  (1, 'soy sauce', 'soy sauce', 1, 'Pantry'),
  (1, 'vinegar', 'vinegar', 1, 'Pantry'),
  (1, 'flour', 'flour', 1, 'Pantry'),
  (1, 'rice', 'rice', 1, 'Pantry'),
  (1, 'pasta', 'pasta', 1, 'Pantry'),
  (1, 'sugar', 'sugar', 1, 'Pantry'),
  (1, 'brown sugar', 'brown sugar', 1, 'Pantry'),
  (1, 'baking powder', 'baking powder', 1, 'Pantry'),
  (1, 'baking soda', 'baking soda', 1, 'Pantry'),
  (1, 'tomato paste', 'tomato paste', 1, 'Pantry'),
  (1, 'canned tomatoes', 'canned tomatoes', 1, 'Pantry'),
  (1, 'chickpeas', 'chickpeas', 1, 'Pantry'),
  (1, 'black beans', 'black beans', 1, 'Pantry'),
  (1, 'honey', 'honey', 1, 'Pantry'),
  (1, 'peanut butter', 'peanut butter', 1, 'Pantry');
